### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.__version__

'2.4.4'

### <a name='1'></a> Ćwiczenie 1
Sprawdź czy wszystkie elementy tablic $A, B, C$ oraz $D$ zwracają wartość logiczną _True_.



```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```



__Wskazówka:__ Użyj funkcji _np.all()._

In [2]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

In [6]:
np.all(D)

np.True_

### <a name='2'></a> Ćwiczenie 2
Sprawdź czy wszystkie elementy tablic $A, B$ oraz $C$ zwracają wartość logiczną _True_ wzdłuż osi z indeksem 1.


```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```



__Wskazówka:__ Użyj funkcji _np.all()_ z parametrem _axis._

In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

In [ ]:
np.all(B, axis=0) # axis=0 : kolumny ; axis:1 : wiersze

array([ True,  True, False,  True])

In [10]:
np.all(B, axis=1) # axis=0 : kolumny ; axis:1 : wiersze

array([ True, False])

### <a name='3'></a> Ćwiczenie 3
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```


__Wskazówka:__ Użyj funkcji _np.any()._

In [16]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [17]:
np.any(A)

np.False_

In [18]:
np.any(B)

np.True_

### <a name='4'></a> Ćwiczenie 4
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_ wzdłuż osi z indeksem 0.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```



__Wskazówka:__ Użyj funkcji _np.any()_ z parametrem _axis._

In [19]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [21]:
np.any(B, axis=0)

array([False,  True, False])

### <a name='5'></a> Ćwiczenie 5
Sprawdź tablicę $A$ pod kątem braków danych (_np.nan_).


```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```


__Wskazówka:__ Użyj funkcji _np.isnan()_.

In [22]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [27]:
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

In [24]:
A[np.isnan(A)]

array([nan, nan])

In [28]:
A[~np.isnan(A)]

array([3., 2., 1., 5., 1., 6.])

### <a name='6'></a> Ćwiczenie 6
Utwórz tablicę zawierającą liczby od 0 do 9.

__Wskazówka:__ Użyj funkcji _np.arange()_.
```


In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### <a name='7'></a> Ćwiczenie 7
Zmień kształt tablicy jednowymiarowej na dwuwymiarową.

__Wskazówka:__ Użyj funkcji _np.reshape()_.
```

In [32]:
jednowymiarowa  = np.arange(12)

In [33]:
jednowymiarowa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
dwuwymiarowa = jednowymiarowa.reshape(4, 3)
dwuwymiarowa

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### <a name='8'></a> Ćwiczenie 8
Wykonaj na tablicy z zadania 7 operacje wycięcia 2 wiersza.

```



In [40]:
dwuwymiarowa[1]

array([3, 4, 5])

In [44]:
dwuwymiarowa[1,]

array([3, 4, 5])

### <a name='9'></a> Ćwiczenie 9
Stwórz tablicę numpy wymiaru _4x4_ wypełnioną zerami. Ustal typ danych na _int_.

__Oczekiwany wynik:__


```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```



__Wskazówka:__ Użyj funkcji _np.zeros()_.

In [45]:
np.zeros(shape=(4, 4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <a name='10'></a> Ćwiczenie 10
Stwórz tablicę numpy wymiaru _10x10_ wypełnioną liczbą 255. Ustal typ danych na _float_.

__Oczekiwany wynik:__


```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```



__Wskazówka:__ Użyj funkcji _np.ones()_ lub _np.full()_.

In [52]:
np.full(255,(10, 10), float)

ValueError: could not broadcast input array from shape (2,) into shape (255,)

In [51]:
np.full(fill_value=255, shape=(10, 10), dtype='float')

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [46]:
np.full(shape=(10, 10), fill_value=255, dtype='float')

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [53]:
# Rozwiązanie 1
np.ones(shape=(10, 10), dtype='float') * 255

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [55]:
np.ones(shape=(10, 10), dtype='float') / 5

array([[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]])